name: 'Security Guardrails'

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  scans:
    name: 'Scans'
    # yamllint disable-line rule:line-length
    uses: garretpatten/security-guardrails/.github/workflows/security-guardrails.yaml@master
    with:
      supply_chain_run: true
      opengrep_run: true
      trufflehog_run: true
    secrets: inherit
